# Generated by Django 5.0.6 on 2024-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Банковская карта', 'Банковская карта')], default='Банковская карта', max_length=150, verbose_name='способ оплаты'),
        ),
    ]
